# Commonly used screens these days easily fit more than 80 characters.
Metrics/LineLength:
  Max: 100

# Too short methods lead to extraction of single-use methods, which can make
# the code easier to read (by naming things), but can also clutter the class
Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 150

Metrics/AbcSize:
  # Enable: false
  Max: 50

Naming/BinaryOperatorParameterName:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: 'indented'

Style/GlobalVars:
  Exclude:
    - 'test/test.rb'

# Rakefile with dsl is not normal ruby code
AllCops:
  Exclude:
    - '**/Rakefile'
    - '**/*.raka'
  TargetRubyVersion: 2.6
