# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: raka 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "raka".freeze
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["yarray".freeze]
  s.date = "2020-03-31"
  s.description = "A extensible, concise and light weight DSL on Rake to automate data processing tasks".freeze
  s.email = "08to09@gmail.com".freeze
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "README.md",
    "VERSION",
    "lib/compile.rb",
    "lib/io.R",
    "lib/output_type.rb",
    "lib/protocol.rb",
    "lib/raka.rb",
    "lib/token.rb"
  ]
  s.homepage = "http://github.com/yarray/raka".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.1.2".freeze
  s.summary = "Rake for data".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4
  end

  if s.respond_to? :add_runtime_dependency then
    s.add_development_dependency(%q<rdoc>.freeze, ["~> 3.12"])
    s.add_development_dependency(%q<bundler>.freeze, ["~> 2.1.0"])
    s.add_development_dependency(%q<juwelier>.freeze, ["~> 2.1.0"])
    s.add_development_dependency(%q<rake>.freeze, ["~> 13.0.0"])
  else
    s.add_dependency(%q<rdoc>.freeze, ["~> 3.12"])
    s.add_dependency(%q<bundler>.freeze, ["~> 2.1.0"])
    s.add_dependency(%q<juwelier>.freeze, ["~> 2.1.0"])
    s.add_dependency(%q<rake>.freeze, ["~> 13.0.0"])
  end
end

