# frozen_string_literal: true
# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

# stub: raka 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = 'raka'
  s.version = '0.2.3'
  s.required_ruby_version = '>= 2.3.0'

  if s.respond_to? :required_rubygems_version=
    s.required_rubygems_version = Gem::Requirement.new('>= 0')
  end
  s.require_paths = ['lib']
  s.authors = ['yarray']
  s.date = '2021-04-26'
  s.description = 'An extensible, concise and light weight DSL on Rake to automate data processing tasks'
  s.email = '08to09@gmail.com'
  s.extra_rdoc_files = [
    'LICENSE',
    'README.md'
  ]
  s.files = [
    'README.md',
    'VERSION',
    'lib/compile.rb',
    'lib/io.R',
    'lib/output_type.rb',
    'lib/protocol.rb',
    'lib/raka.rb',
    'lib/token.rb'
  ]
  s.homepage = 'http://github.com/yarray/raka'
  s.licenses = ['MIT']
  s.rubygems_version = '3.1.2'
  s.summary = 'Rake for data'

  s.specification_version = 4 if s.respond_to? :specification_version

  if s.respond_to? :add_runtime_dependency
    s.add_development_dependency('bundler', ['~> 2.1.0'])
    s.add_development_dependency('juwelier', ['~> 2.1.0'])
    s.add_development_dependency('rake', ['~> 13.0.0'])
    s.add_development_dependency('rdoc', ['~> 3.12'])
  else
    s.add_dependency('rake', ['~> 13.0.0'])
  end
end
