# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: raka 0.4.0 ruby lib

Gem::Specification.new do |s|
  s.name = "raka".freeze
  s.version = "0.4.0".freeze

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["yarray".freeze]
  s.date = "1980-01-02"
  s.description = "An extensible, concise and light weight DSL on Rake to automate data processing tasks".freeze
  s.email = "08to09@gmail.com".freeze
  s.executables = ["raka".freeze]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "README.md",
    "VERSION",
    "bin/raka",
    "lib/raka.rb",
    "lib/raka/compile.rb",
    "lib/raka/interface.rbs",
    "lib/raka/lang/duckdb/impl.rb",
    "lib/raka/lang/psql/impl.rb",
    "lib/raka/lang/python/impl.rb",
    "lib/raka/lang/r/impl.rb",
    "lib/raka/lang/shell/impl.rb",
    "lib/raka/output_type.rb",
    "lib/raka/protocol.rb",
    "lib/raka/token.rb"
  ]
  s.homepage = "http://github.com/yarray/raka".freeze
  s.licenses = ["MIT".freeze]
  s.required_ruby_version = Gem::Requirement.new(">= 2.3.0".freeze)
  s.rubygems_version = "3.6.9".freeze
  s.summary = "Rake for data".freeze

  s.specification_version = 4

  s.add_runtime_dependency(%q<rake>.freeze, ["~> 13.3.0".freeze])
  s.add_development_dependency(%q<bundler>.freeze, [">= 2.1.0".freeze])
  s.add_development_dependency(%q<juwelier>.freeze, ["~> 2.4.0".freeze])
  s.add_development_dependency(%q<rdoc>.freeze, [">= 6.3.1".freeze])
  s.add_development_dependency(%q<reek>.freeze, ["~> 6.0".freeze])
  s.add_development_dependency(%q<rubocop>.freeze, ["~> 1.79.0".freeze])
  s.add_development_dependency(%q<test-unit>.freeze, ["~> 3.7.0".freeze])
end

