rule ::= target "=" (dependencies "|")* protocol ("|" post_target)*

target ::= ext "." ltoken ("." ltoken)*

dependency ::= rexpr | template

post_target ::= rexpr | template

dependencies ::= "[]" | "[" dependency ("," dependency)* "]"

rexpr ::= ext "." rtoken ("." rtoken)*

ltoken ::= word | word "[" pattern "]"
rtoken ::= word | word "(" template ")"

word ::= ("_" | letter) ( letter | digit | "_" )*

protocol ::= ("shell" | "r" | "psql" | "py" ) ("*" template | BLOCK ) | "run" BLOCK